package com.sitetracker.fleet.controller;

import com.sitetracker.fleet.pojo.Bus;
import com.sitetracker.fleet.pojo.BusCondition;
import com.sitetracker.fleet.service.BusService;
import org.json.JSONObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

import static com.sitetracker.fleet.constants.BusStatus.READY_FOR_USE;

@RestController
public class BusController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BusService busService;

    JSONObject jo;
    String error;

    @GetMapping(path="/all")
    @ResponseBody
    public  List<Bus> getAllBuses() {
        // This returns a JSON or XML with the users
        return busService.getAllBuses();
    }

    @GetMapping(path="/every")
    public ResponseEntity<Optional> getEvery() {
        try {
            List<Bus> buses = busService.getAllBuses();
            if (!buses.isEmpty()) {
                return new ResponseEntity<>(Optional.of(buses), HttpStatus.OK);
            } else {
                error = "{\"error\": \"Buses not found\"}";
                jo = new JSONObject(error);
                return new ResponseEntity<>(Optional.of(jo.toString()), HttpStatus.NOT_FOUND);
            }
        } catch (Exception e) {
            error = "{\"error\": \"Something went wrong in the backend!!\"}";
            jo = new JSONObject(error);
            return new ResponseEntity<>(Optional.of(jo.toString()), HttpStatus.BAD_REQUEST);
        }
    }

    @GetMapping(path="/calculate")
    public ResponseEntity<Optional> getResaleValue(@RequestParam(name = "id") Long id){
        try {
            Bus bus = busService.findBus(id);
//            System.out.println(bus.toString());
            List<BusCondition> conditions = busService.getBusConditions();
            double odometerFactor = conditions.get(0).getPrice_percentage();
            double increasedAirConditioningRate = conditions.get(1).getPrice_percentage();
            double ageIncreasedRate = conditions.get(2).getPrice_percentage();
            System.out.println(bus.getStatus());
            if (bus.getStatus() == READY_FOR_USE) {
                double startingPrice = busService.getStartingSalePrice(bus.getCapacity());

                if (bus.getOdometer_reading() > 100000) {
                    double extraMiles = bus.getOdometer_reading() - 100000;
                    startingPrice = startingPrice + (extraMiles * odometerFactor);
                }

                if (bus.isAir_conditioning()) {
                    startingPrice = startingPrice + (startingPrice * increasedAirConditioningRate);
                }

                if (bus.getYear() > 1972) {
                    startingPrice = startingPrice + (startingPrice * ageIncreasedRate);
                }

                return new ResponseEntity<>(Optional.of(startingPrice), HttpStatus.OK);
            } else {
                return new ResponseEntity<>(Optional.of(0), HttpStatus.OK);
            }
        }catch (Exception e) {
            error = "{\"error\": \"Something went wrong in the backend!!\"}";
            e.printStackTrace();
            jo = new JSONObject(error);
            return new ResponseEntity<>(Optional.of(0), HttpStatus.BAD_REQUEST);
        }
    }

    @PostMapping(path="/save")
    public ResponseEntity<Optional> saveData(@RequestBody Bus bus) {
        System.out.println(bus.toString());
        busService.saveBus(bus);
        error = "{\"Success\": \"Data Saved\"}";
        jo = new JSONObject(error);
        return new ResponseEntity<>(Optional.of(jo.toString()), HttpStatus.OK);
    }

}
